#
# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0
#

copyright: Copyright (c) Mainflux
repo_url: https://github.com/mainflux/docs
site_description: Mainflux IoT System
site_name: Mainflux
theme: readthedocs

extra:
  logo: docs/img/logo.png
  author:
    github: mainflux/mainflux
    twitter: mainflux

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"

nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Getting Started: getting-started.md
  - Provision: provision.md
  - Messaging: messaging.md
  - Storage: storage.md
  - LoRa: lora.md
  - OPC-UA: opcua.md
  - Edge: edge.md
  - Security: security.md
  - Authentication: authentication.md
  - CLI: cli.md
  - API: api.md
  - Bootstrap: bootstrap.md
  - Twins: twins.md
  - Tracing: tracing.md
  - Rules: rules.md
  - Developer's Guide: dev-guide.md
  - Kubernetes: kubernetes.md
  - Benchmark: benchmark.md
